### ISSUE TITLE
Bug report: Unable to view vibecheck dashboard after logging in through Spotify

### ISSUE THREAD

**Issue by rishienandhan3** [gcivil-nyu-org/Wednesday-Fall2023-Team-1#200]
Hi team, 

I am unable to view the app dashboard after successfully logging in through my Spotify account (was whitelisted by Adel). I get the following error when I am redirected to the app dashboard after Spotify login and agreeing to the terms and conditions:
'SpotifyException at /dashboard/
http status: 400, code:-1 - https://api.spotify.com/v1/recommendations?limit=5:
 invalid request, reason: None'

Screenshot attached: 
<img width="1552" alt="Screenshot 2023-11-17 at 3 22 06 PM" src="https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-1/assets/143848239/bc278e1a-8e7d-4f57-987c-400ae4b23d9c">

**Comment by yp2353** [comment]
Yes it will throw exception if your account is brand new/has not listened to any songs :(

**Comment by rishienandhan3** [comment]
I listened to ~10songs on my spotify account and tried logging in to the vibecheck website again. Unfortunately, it gives me the same error. Is there a min number of songs I must listen to before I can see my dashboard?

**Comment by yp2353** [comment]
This bug is fixed
