### ISSUE TITLE
Testing Party: User login error

### ISSUE THREAD

**Issue by jkcny** [gcivil-nyu-org/Wednesday-Fall2023-Team-1#201]
After login with my spotify account, I got the following error
![image](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-1/assets/90436243/4ea2ada6-7efc-45ca-96f4-b6167ae40336)

**Comment by jkcny** [comment]
Seems like it's similar to this bug: https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-1/issues/200
My account is new

**Comment by khamseaffan** [comment]
your account mail ID is not registered on developer list, we need to add that, than only you can get access
