### ISSUE TITLE
Testing Party: Vibe Check too long / Error

### ISSUE THREAD

**Issue by Chinnu1103** [gcivil-nyu-org/Wednesday-Fall2023-Team-1#203]
I logged into the website and it took about 15 minutes for it to try to calculate my vibe (spinning thingy)
And then it showed this error:

![image](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-1/assets/32939338/aeffb629-54bd-411b-9ecc-13c5eb8df18c)

**Comment by yp2353** [comment]
It should take about 5 minutes. Does it work when you try again?

**Comment by Chinnu1103** [comment]
Yes, I retried and this time it worked

**Comment by Chinnu1103** [comment]
Although now, there is no description of my vibe:

![image](https://github.com/gcivil-nyu-org/Wednesday-Fall2023-Team-1/assets/32939338/f4c9f741-2ac0-4262-9a6c-c9f8c2d67a25)

**Comment by yp2353** [comment]
Good to hear you're able to log in and get the vibe!
It does seem the api was down so we couldn't get a description, we will look into that, thanks.
