### ISSUE TITLE
Test Party: Login Loop

### ISSUE THREAD

**Issue by Chinnu1103** [gcivil-nyu-org/Wednesday-Fall2023-Team-1#204]
Hi, I think Adel face this issue during the test party demo as well?
Bu when I click on login, and agree for spoitfy to get my data, it just redirects me to the home page again and asks me to login.
BTW Im added to the list of developers and I was able to access the website earlier

**Comment by yp2353** [comment]
Can you try to login again? This issue resolves itself after some time, I was just able to login
