### ISSUE TITLE
Cache File Handler SP OAuth Token

### ISSUE THREAD

**Issue by adeldelvalle** [gcivil-nyu-org/Wednesday-Fall2023-Team-1#52]
Points: 3

**Comment by adeldelvalle** [comment]
**User story**

User Log-in Story

**Acceptance criteria**

Multiple users can log-in and authenticate with Spotify app, and the application will handle their sessions with cache file handling. 

**Definition of Done**

It is deployed and the different users that get into the application are able to sign in, be redirected back and see everything personalized to their account.

**Comment by BoyanXu** [comment]
Django Session:

https://docs.djangoproject.com/en/4.2/topics/http/sessions/
